### ISSUE TITLE
Pass Sandbox JSON as env variable

### ISSUE THREAD

**Issue by graboskyc** [QualiSystems/Sandbox-Jenkins-Plugin#9]
The sandbox GUID is passed in via the ENV variable. This would then require an additional API call to the Quali server to get the sandbox details. If you return the JSON on sandbox start, it would prevent this API call and the need to store Quali credentials in the tests.

**Comment by TomerAdmon** [comment]
now you can use the SANDBOX_DETAILS environment variable to get the sandbox information
